### ISSUE TITLE
Error: BiocParallel errors

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [MNStokholm/GEDI#1]
Hi @MNStokholm 

I am trying to use GEDI as follows for batch correction and getting the error:

```
> counts_gedi = BatchCorrection(Data = counts, batch = samples$batch, status = samples$condition, visualize = TRUE, boxplot.type="rle")

Error: BiocParallel errors 1 remote errors, element index: 1 1 unevaluated and other errors first remote error: missing value where TRUE/FALSE needed
```
I looked into [https://github.com/Bioconductor/BiocParallel](url) and tried for potential solutions, but did not help.

Any pointers please?

Thanks.

**Comment by MNStokholm** [comment]
Hi Gurpreet Kaur,
I have never run into that specific error before. Are there any missing
values or other "funny stuff" in your data? It would be easier to help if I
can replicate the error.

What you could do is to copy the GEDI repository to your computer and add
print statements to the BatchCorrection function to pinpoint where the
error happens. I will be happy to help if the data isn't too sensitive!

Hope you find a solution and that you enjoy my package.

Best Regards,
Mathias
MNStokholm



Den tir. 14. jun. 2022 kl. 22.11 skrev Gurpreet Kaur <
***@***.***>:
