### ISSUE TITLE
integration RNAseq and Microarray

### ISSUE THREAD

**Issue by Maryan12m** [MNStokholm/GEDI#11]
Hi,
Thank you for the great package.
How is the data integration step done by the GEDI package?
Is it done through the following simple script?
data1=RNAseq and data2=affymetrix and ID=ENSemble id
ds <- merge(data1, data2, by=ID)
After following all steps of your package
In the last stage, the integration accuracy was 80%
How can I increase this value to 100?
res <- VerifyGEDI(X = cData, y = status, batch = batch, model = "logistic")
Number of features:  1                                                        
ENSGALG00010009603 
Worst score across batches:  0.8

**Comment by MNStokholm** [comment]
Integration is a combination of the steps:
1. Make sure all datasets have the same labels, e.g. ENSemble id
2. merge(data1, data2, by = ID) as you said
3. Remove batch effect

The answer to your second question is that it is simply unrealistic to strive for a score of 100%. The score reflects the percent accuracy that the model can predict the state of a cell. In real data, models rarely predict correctly 100% of the time. I would be more than happy with 80%.

That being said, there are a few things outside the GEDI package that may increase the score:

1. VerifyGEDI uses a logistic regression model. Using a different model may result in a better performance. Although you should be careful that you don't overfit your model.
2. Remaining batch effects may affect the model performance. Look batch effect removal methods other than ComBat (used by GEDI).

Hope this helps

**Comment by Maryan12m** [comment]
Thanks a lot,Is it necessary to remove the batch effect before merging or after the merging stage?
What other combat method do you think is more suitable for removing the batch effect?
What do you mean by residual effects? Doesn't the combat  remove the effects of a batch?
I removed the batch effect after merging, and I have attached a picture of it.But due to the high variance in one of the variables, I want to do only the batch effect removal and validation steps. But after removing that variable from the merged data(remove sample 16 of dataset) and running the batch effect removal step, I encounter this error:PATH_TO_DATA_FOLDERS <- "/home/linux/Downloads/"
pheno <- read.table(paste(PATH_TO_DATA_FOLDERS,"/phenoint.txt",sep = ""), header = TRUE)
dat <- read.table(paste(PATH_TO_DATA_FOLDERS,"/Data_inttegration.txt",sep = ""), header = TRUE)
status = pheno$status
batch = pheno$batch
cData <- BatchCorrection(Data = dat, batch = pheno$batch, status = pheno$status, visualize = TRUE)Found2batchesAdjusting for0covariate(s) or covariate level(s)Standardizing Data across genesFitting L/S model and finding priorsFinding parametric adjustmentsError: BiocParallel errors  1 remote errors, element index: 1  1 unevaluated and other errors  first remote error:Error in while (change > conv) {: missing value where TRUE/FALSE needed
Please guide me on how I can perform the last two steps by removing a sample from the merged data.
    On Friday, November 15, 2024 at 12:22:10 PM GMT+3:30, Mathias N. Stokholm ***@***.***> wrote:  
 
 


Closed #11 as completed.

**Comment by Maryan12m** [comment]
Thanks a lot,
What other combat method do you think is more suitable for removing the batch effect?
What do you mean by residual effects? Doesn't the combat  remove the effects of a batch?
I removed the batch effect after merging, and I have attached a picture of it.But due to the high variance in one of the variables, I want to do only the batch effect removal and validation steps. But after removing that variable from the merged data(remove sample 16 of dataset) and running the batch effect removal step, I encounter this error:PATH_TO_DATA_FOLDERS <- "/home/linux/Downloads/"
pheno <- read.table(paste(PATH_TO_DATA_FOLDERS,"/phenoint.txt",sep = ""), header = TRUE)
dat <- read.table(paste(PATH_TO_DATA_FOLDERS,"/Data_inttegration.txt",sep = ""), header = TRUE)
status = pheno$status
batch = pheno$batch
cData <- BatchCorrection(Data = dat, batch = pheno$batch, status = pheno$status, visualize = TRUE)Found2batchesAdjusting for0covariate(s) or covariate level(s)Standardizing Data across genesFitting L/S model and finding priorsFinding parametric adjustmentsError: BiocParallel errors  1 remote errors, element index: 1  1 unevaluated and other errors  first remote error:Error in while (change > conv) {: missing value where TRUE/FALSE needed
Please guide me on how I can perform the last two steps by removing a sample from the merged data.
