### ISSUE TITLE
ReadGE not reading in files

### ISSUE THREAD

**Issue by adeizadavid** [MNStokholm/GEDI#2]
I am trying to merge RNAseq files only but i keep getting `Error in read.table(paste(dataFolder.path, "/RawCounts.txt", sep = ""),  : 
  duplicate 'row.names' are not allowed`

Are there specific format for the RawCounts.txt. Can it accept csv or tsv in .txt. I dont intend to use the biomart feature as i already have the gene names. 

thanks

Oh i fixed it. Had to do with the rownames duplicate and starting the column names from the first columns.

**Comment by MNStokholm** [comment]
Happy to hear that you fixed it
