### ISSUE TITLE
GEDi with microarray with no annotation package in Bioconductor

### ISSUE THREAD

**Issue by boufn** [MNStokholm/GEDI#9]
Hi 
I am wondering if there is a way to run the readGE function using a microarray that does not have an annotation package (pd. xxx) in Bioconductor?
Thank you

**Comment by MNStokholm** [comment]
The only thing readGE does is reading datasets and storing them in a list. So if you use microarray data other than Affymetrix or Agilent, I suggest you read them in using other packages. If you store the data in a list, you can still use the remaining functions in GEDI.

Hope this helps.

**Comment by boufn** [comment]
Yes actually it does
Thank you
Nadia

From: Mathias N. Stokholm ***@***.***>
Date: Tuesday, June 4, 2024 at 10:57 AM
To: MNStokholm/GEDI ***@***.***>
Cc: Nadia Boufaied ***@***.***>, Author ***@***.***>
Subject: Re: [MNStokholm/GEDI] GEDi with microarray with no annotation package in Bioconductor (Issue #9)

The only thing readGE does is reading datasets and storing them in a list. So if you use microarray data other than Affymetrix or Agilent, I suggest you read them in using other packages. If you store the data in a list, you can still use the remaining functions in GEDI.

Hope this helps.
